{% set name = "flask-apscheduler" %}
{% set pkg_name = "Flask-APScheduler" %}
{% set version = "1.13.0" %}
{% set sha256 = "19555d6761990f110678aa584ab3ad0e7e698238e6ff60d8f38ab1322bda14c2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - apscheduler >=3.2.0,<4.0.0
    - flask >=0.10.1
    - python-dateutil >=2.4.2

test:
  imports:
    - flask_apscheduler

about:
  home: https://github.com/viniciuschiele/flask-apscheduler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flask-APScheduler is a Flask extension which adds support for the APScheduler
  description: |
    Flask-APScheduler is a Flask extension which adds support for the APScheduler.
    Advanced Python Scheduler (APScheduler) is a Python library that lets you schedule your Python 
    code to be executed later, either just once or periodically. You can add new jobs or remove old 
    ones on the fly as you please. If you store your jobs in a database, they will also survive 
    scheduler restarts and maintain their state. When the scheduler is restarted, it will then run 
    all the jobs it should have run while it was offline [1].

    Among other things, APScheduler can be used as a cross-platform, application specific replacement 
    to platform specific schedulers, such as the cron daemon or the Windows task scheduler. Please 
    note, however, that APScheduler is not a daemon or service itself, nor does it come with any 
    command line tools. It is primarily meant to be run inside existing applications. That said, 
    APScheduler does provide some building blocks for you to build a scheduler service or to run a 
    dedicated scheduler process.
  doc_url: https://apscheduler.readthedocs.io
  dev_url: https://github.com/viniciuschiele/flask-apscheduler

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
    - edetec
