travis:
  secure:
    BINSTAR_TOKEN: GN1o1HzHRdLmQD1tKRow+rbo6C/VslwymqDpcU5HLFDLdO1qtztF6W2EoJc+uCDyv6xnydPt7RglxI30zboMnGq84RETubhNMNQF0Qqi0JHO8eI01LUiHCXDWd51RWoTH1/klrydsJ2FxQvn1PrhTdpFdjxWvD/PJ7548OMG87jg1wRlU9jznOet3bdij7v2oz+60n2o7TVT25ESS++GeaxtVWYhl1HDgtQxa+oDqeZsC7G6F+lbO6RChpyK26pHRIT8LQnlHbsKHEvo86xndIQJ7dwKShC+8UX2iwWocPsFDBMmKvWrXhIWRZVTjfSEF3uBTy2ZqJ0B3nxLSKTpb9xD3/jfPnTCDviEjmt71hbWQABcQ1q2blbSsZveHOVJukz6Qv/PdSH58wnNymCiQsg3J5SLnd22UnxYUijSQVkAMrR2xK8It15woartaCepiOYaCR46MENl3EaSKq6zY4BZP0sLZTdL0Q1CGHspBryz+BH0Eoeb+H7ipRT97z4zZPlxqR9/lgL1q17m4usjWIRyXS2OGLygWcb8IGTYvvywPfQqIbDS4rhBwqSdh9v9S4/07UHM6dqTEYD8iNt73kk6yLv8ALwTNbs8j46ms6C7KvHtfWvYH94E5e0o4jRZmMVQvfJpVTjU6um0m3rd0cEbqi8Sb3rgiDxDFapR5yc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
